// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcPnreue9PonbZPg56CuB7QIILxK7bEes',
    appId: '1:449042898541:web:5bbb78ceba9277970de964',
    messagingSenderId: '449042898541',
    projectId: 'final-project-2202b',
    authDomain: 'final-project-2202b.firebaseapp.com',
    storageBucket: 'final-project-2202b.firebasestorage.app',
    measurementId: 'G-N7GTXP4YGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNkbttfv7huhackI_UCLl_NGxHoVBePA',
    appId: '1:449042898541:android:d84d90bc2147b1cf0de964',
    messagingSenderId: '449042898541',
    projectId: 'final-project-2202b',
    storageBucket: 'final-project-2202b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATIiQpFJ0FgSG-j_71alWpet7MXhfDCls',
    appId: '1:449042898541:ios:0dcfe38d59e552c50de964',
    messagingSenderId: '449042898541',
    projectId: 'final-project-2202b',
    storageBucket: 'final-project-2202b.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATIiQpFJ0FgSG-j_71alWpet7MXhfDCls',
    appId: '1:449042898541:ios:0dcfe38d59e552c50de964',
    messagingSenderId: '449042898541',
    projectId: 'final-project-2202b',
    storageBucket: 'final-project-2202b.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcPnreue9PonbZPg56CuB7QIILxK7bEes',
    appId: '1:449042898541:web:6d8c5ba17dedbdf50de964',
    messagingSenderId: '449042898541',
    projectId: 'final-project-2202b',
    authDomain: 'final-project-2202b.firebaseapp.com',
    storageBucket: 'final-project-2202b.firebasestorage.app',
    measurementId: 'G-85KE15GQDE',
  );
}
